// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Cargo", Schema = "pamec")]
    public partial class Cargo
    {
        public Cargo()
        {
            Menu_Cargo = new HashSet<Menu_Cargo>();
            Usuario_Cargo = new HashSet<Usuario_Cargo>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(100)]
        public string nombre { get; set; }
        [StringLength(250)]
        public string descripcion { get; set; }
        [StringLength(250)]
        public string responsabilidades { get; set; }

        [InverseProperty("idCargoNavigation")]
        public virtual ICollection<Menu_Cargo> Menu_Cargo { get; set; }
        [InverseProperty("idCargoNavigation")]
        public virtual ICollection<Usuario_Cargo> Usuario_Cargo { get; set; }
    }
}