// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Constante", Schema = "pamec")]
    public partial class Constante
    {
        public Constante()
        {
            EntidadidTipoDocRepresLegalNavigation = new HashSet<Entidad>();
            EntidadidTipoDocumentoNavigation = new HashSet<Entidad>();
            EntidadidTipoPrestadorNavigation = new HashSet<Entidad>();
            RegistroPAMECidAlcanceMejoramientoNavigation = new HashSet<RegistroPAMEC>();
            RegistroPAMECidEstadoEvaluacionSegumientoNavigation = new HashSet<RegistroPAMEC>();
            RegistroPAMECidGrupoClasificacionNavigation = new HashSet<RegistroPAMEC>();
            RegistroSIC = new HashSet<RegistroSIC>();
            SeguimientoPAMECidAccionATomarNavigation = new HashSet<SeguimientoPAMEC>();
            SeguimientoPAMECidDetalleAccionAdminNavigation = new HashSet<SeguimientoPAMEC>();
            SeguimientoPAMECidResultadoEjecucionNavigation = new HashSet<SeguimientoPAMEC>();
            SeguimientoPAMECidTipoVisitaNavigation = new HashSet<SeguimientoPAMEC>();
            SeguimientoPAMECrealizoReportesPAMECNavigation = new HashSet<SeguimientoPAMEC>();
            SeguimientoSICidDetalleAccionAdminNavigation = new HashSet<SeguimientoSIC>();
            SeguimientoSICidTipoVisitaNavigation = new HashSet<SeguimientoSIC>();
            UsuarioidTipoIdentificaiconNavigation = new HashSet<Usuario>();
            UsuariotipoVinculacionNavigation = new HashSet<Usuario>();
        }

        [Key]
        public int id { get; set; }
        public int idPadre { get; set; }
        public int codigo { get; set; }
        [Required]
        [StringLength(100)]
        public string nombre { get; set; }
        [Required]
        [StringLength(100)]
        public string descripcion { get; set; }
        public bool estado { get; set; }

        [InverseProperty(nameof(Entidad.idTipoDocRepresLegalNavigation))]
        public virtual ICollection<Entidad> EntidadidTipoDocRepresLegalNavigation { get; set; }
        [InverseProperty(nameof(Entidad.idTipoDocumentoNavigation))]
        public virtual ICollection<Entidad> EntidadidTipoDocumentoNavigation { get; set; }
        [InverseProperty(nameof(Entidad.idTipoPrestadorNavigation))]
        public virtual ICollection<Entidad> EntidadidTipoPrestadorNavigation { get; set; }
        [InverseProperty(nameof(RegistroPAMEC.idAlcanceMejoramientoNavigation))]
        public virtual ICollection<RegistroPAMEC> RegistroPAMECidAlcanceMejoramientoNavigation { get; set; }
        [InverseProperty(nameof(RegistroPAMEC.idEstadoEvaluacionSegumientoNavigation))]
        public virtual ICollection<RegistroPAMEC> RegistroPAMECidEstadoEvaluacionSegumientoNavigation { get; set; }
        [InverseProperty(nameof(RegistroPAMEC.idGrupoClasificacionNavigation))]
        public virtual ICollection<RegistroPAMEC> RegistroPAMECidGrupoClasificacionNavigation { get; set; }
        [InverseProperty("idFuenteAnalisisNavigation")]
        public virtual ICollection<RegistroSIC> RegistroSIC { get; set; }
        [InverseProperty(nameof(SeguimientoPAMEC.idAccionATomarNavigation))]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMECidAccionATomarNavigation { get; set; }
        [InverseProperty(nameof(SeguimientoPAMEC.idDetalleAccionAdminNavigation))]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMECidDetalleAccionAdminNavigation { get; set; }
        [InverseProperty(nameof(SeguimientoPAMEC.idResultadoEjecucionNavigation))]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMECidResultadoEjecucionNavigation { get; set; }
        [InverseProperty(nameof(SeguimientoPAMEC.idTipoVisitaNavigation))]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMECidTipoVisitaNavigation { get; set; }
        [InverseProperty(nameof(SeguimientoPAMEC.realizoReportesPAMECNavigation))]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMECrealizoReportesPAMECNavigation { get; set; }
        [InverseProperty(nameof(SeguimientoSIC.idDetalleAccionAdminNavigation))]
        public virtual ICollection<SeguimientoSIC> SeguimientoSICidDetalleAccionAdminNavigation { get; set; }
        [InverseProperty(nameof(SeguimientoSIC.idTipoVisitaNavigation))]
        public virtual ICollection<SeguimientoSIC> SeguimientoSICidTipoVisitaNavigation { get; set; }
        [InverseProperty(nameof(Usuario.idTipoIdentificaiconNavigation))]
        public virtual ICollection<Usuario> UsuarioidTipoIdentificaiconNavigation { get; set; }
        [InverseProperty(nameof(Usuario.tipoVinculacionNavigation))]
        public virtual ICollection<Usuario> UsuariotipoVinculacionNavigation { get; set; }
    }
}