// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Criterio_TipoDocumento", Schema = "pamec")]
    public partial class Criterio_TipoDocumento
    {
        public Criterio_TipoDocumento()
        {
            Documento_RegistroPAMEC_RegistroSIC = new HashSet<Documento_RegistroPAMEC_RegistroSIC>();
        }

        [Key]
        public int id { get; set; }
        public int idTipoDocumento { get; set; }
        public int idCriterio { get; set; }
        public bool rutaCritica { get; set; }
        public bool esObligatorio { get; set; }
        public bool estado { get; set; }

        [ForeignKey(nameof(idCriterio))]
        [InverseProperty(nameof(Criterio.Criterio_TipoDocumento))]
        public virtual Criterio idCriterioNavigation { get; set; }
        [ForeignKey(nameof(idTipoDocumento))]
        [InverseProperty(nameof(TipoDocumento.Criterio_TipoDocumento))]
        public virtual TipoDocumento idTipoDocumentoNavigation { get; set; }
        [InverseProperty("idCriterioTipoDocumentoNavigation")]
        public virtual ICollection<Documento_RegistroPAMEC_RegistroSIC> Documento_RegistroPAMEC_RegistroSIC { get; set; }
    }
}