// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Dependencia", Schema = "pamec")]
    public partial class Dependencia
    {
        public Dependencia()
        {
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(150)]
        public string nombre { get; set; }

        [InverseProperty("idDpendenciaNavigation")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}