// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Documento_RegistroPAMEC_RegistroSIC", Schema = "pamec")]
    public partial class Documento_RegistroPAMEC_RegistroSIC
    {
        [Key]
        public int id { get; set; }
        public int? idRegistroPAMEC { get; set; }
        public int? idRegistroSIC { get; set; }
        public int idCriterioTipoDocumento { get; set; }
        public bool? esAprobado { get; set; }
        [StringLength(4000)]
        public string observaciones { get; set; }
        [StringLength(50)]
        public string idGestorDocumental { get; set; }
        [Required]
        public byte[] base64 { get; set; }
        [StringLength(100)]
        public string nombre { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaCreacion { get; set; }
        [Column(TypeName = "date")]
        public DateTime? fechaModificacion { get; set; }
        public bool? estado { get; set; }

        [ForeignKey(nameof(idCriterioTipoDocumento))]
        [InverseProperty(nameof(Criterio_TipoDocumento.Documento_RegistroPAMEC_RegistroSIC))]
        public virtual Criterio_TipoDocumento idCriterioTipoDocumentoNavigation { get; set; }
        [ForeignKey(nameof(idRegistroPAMEC))]
        [InverseProperty(nameof(RegistroPAMEC.Documento_RegistroPAMEC_RegistroSIC))]
        public virtual RegistroPAMEC idRegistroPAMECNavigation { get; set; }
        [ForeignKey(nameof(idRegistroSIC))]
        [InverseProperty(nameof(RegistroSIC.Documento_RegistroPAMEC_RegistroSIC))]
        public virtual RegistroSIC idRegistroSICNavigation { get; set; }
    }
}