// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Menu", Schema = "pamec")]
    public partial class Menu
    {
        public Menu()
        {
            Menu_Cargo = new HashSet<Menu_Cargo>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string nombre { get; set; }
        [Required]
        [StringLength(500)]
        public string descripcion { get; set; }
        [Required]
        [StringLength(100)]
        public string link { get; set; }

        [InverseProperty("idMenuNavigation")]
        public virtual ICollection<Menu_Cargo> Menu_Cargo { get; set; }
    }
}