// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Menu_Cargo", Schema = "pamec")]
    public partial class Menu_Cargo
    {
        [Key]
        public int id { get; set; }
        public int idMenu { get; set; }
        public int idCargo { get; set; }

        [ForeignKey(nameof(idCargo))]
        [InverseProperty(nameof(Cargo.Menu_Cargo))]
        public virtual Cargo idCargoNavigation { get; set; }
        [ForeignKey(nameof(idMenu))]
        [InverseProperty(nameof(Menu.Menu_Cargo))]
        public virtual Menu idMenuNavigation { get; set; }
        [InverseProperty("idNavigation")]
        public virtual Permiso Permiso { get; set; }
    }
}