// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("MiembroComision", Schema = "pamec")]
    public partial class MiembroComision
    {
        [Key]
        public int id { get; set; }
        public int idRegistro { get; set; }
        public int idUsuarioCargo { get; set; }

        [ForeignKey(nameof(idRegistro))]
        [InverseProperty(nameof(Registro.MiembroComision))]
        public virtual Registro idRegistroNavigation { get; set; }
        [ForeignKey(nameof(idUsuarioCargo))]
        [InverseProperty(nameof(Usuario_Cargo.MiembroComision))]
        public virtual Usuario_Cargo idUsuarioCargoNavigation { get; set; }
    }
}