// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("RegistroSIC", Schema = "pamec")]
    public partial class RegistroSIC
    {
        public RegistroSIC()
        {
            Documento_RegistroPAMEC_RegistroSIC = new HashSet<Documento_RegistroPAMEC_RegistroSIC>();
        }

        [Key]
        public int id { get; set; }
        public int idRegistro { get; set; }
        public bool presentoReportes { get; set; }
        [Required]
        [StringLength(4000)]
        public string motivosNoEnvioReporte { get; set; }
        public bool realizoAnalisisInfo { get; set; }
        [Required]
        [StringLength(4000)]
        public string motivosNoEnvioAnalisisInfo { get; set; }
        public int idFuenteAnalisis { get; set; }
        [Required]
        [StringLength(20)]
        public string otraFuenteAnalisis { get; set; }
        [Required]
        [StringLength(4)]
        public string porcentajeEjecucion { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaCreacion { get; set; }

        [ForeignKey(nameof(idFuenteAnalisis))]
        [InverseProperty(nameof(Constante.RegistroSIC))]
        public virtual Constante idFuenteAnalisisNavigation { get; set; }
        [ForeignKey(nameof(idRegistro))]
        [InverseProperty(nameof(Registro.RegistroSIC))]
        public virtual Registro idRegistroNavigation { get; set; }
        [InverseProperty("idRegistroSICNavigation")]
        public virtual ICollection<Documento_RegistroPAMEC_RegistroSIC> Documento_RegistroPAMEC_RegistroSIC { get; set; }
    }
}