// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("RegistroPAMEC", Schema = "pamec")]
    public partial class RegistroPAMEC
    {
        public RegistroPAMEC()
        {
            Documento_RegistroPAMEC_RegistroSIC = new HashSet<Documento_RegistroPAMEC_RegistroSIC>();
        }

        [Key]
        public int id { get; set; }
        public int idRegistro { get; set; }
        public int idGrupoClasificacion { get; set; }
        public bool realizoReportes { get; set; }
        [Required]
        [StringLength(4)]
        public string anoVigencia { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaFin { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaReporte { get; set; }
        [Required]
        [StringLength(4000)]
        public string motivosNoEnvioReporte { get; set; }
        public int idAlcanceMejoramiento { get; set; }
        public int idEstadoEvaluacionSegumiento { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaCreacion { get; set; }

        [ForeignKey(nameof(idAlcanceMejoramiento))]
        [InverseProperty(nameof(Constante.RegistroPAMECidAlcanceMejoramientoNavigation))]
        public virtual Constante idAlcanceMejoramientoNavigation { get; set; }
        [ForeignKey(nameof(idEstadoEvaluacionSegumiento))]
        [InverseProperty(nameof(Constante.RegistroPAMECidEstadoEvaluacionSegumientoNavigation))]
        public virtual Constante idEstadoEvaluacionSegumientoNavigation { get; set; }
        [ForeignKey(nameof(idGrupoClasificacion))]
        [InverseProperty(nameof(Constante.RegistroPAMECidGrupoClasificacionNavigation))]
        public virtual Constante idGrupoClasificacionNavigation { get; set; }
        [ForeignKey(nameof(idRegistro))]
        [InverseProperty(nameof(Registro.RegistroPAMEC))]
        public virtual Registro idRegistroNavigation { get; set; }
        [InverseProperty("idRegistroPAMECNavigation")]
        public virtual ICollection<Documento_RegistroPAMEC_RegistroSIC> Documento_RegistroPAMEC_RegistroSIC { get; set; }
    }
}