// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Registro", Schema = "pamec")]
    public partial class Registro
    {
        public Registro()
        {
            MiembroComision = new HashSet<MiembroComision>();
            RegistroPAMEC = new HashSet<RegistroPAMEC>();
            RegistroSIC = new HashSet<RegistroSIC>();
            SeguimientoPAMEC = new HashSet<SeguimientoPAMEC>();
            SeguimientoSIC = new HashSet<SeguimientoSIC>();
        }

        [Key]
        public int id { get; set; }
        [Column(TypeName = "date")]
        public DateTime fecha { get; set; }
        public int idCoordinadorComision { get; set; }
        public int idResponsablePAMEC { get; set; }
        public int idResponsableSIC { get; set; }
        public bool aceptaTratamientoDatos { get; set; }
        public bool apruebaAuditoriaInformacion { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaCreacion { get; set; }
        public int idEstadoRegistro { get; set; }

        [ForeignKey(nameof(idResponsablePAMEC))]
        [InverseProperty(nameof(Responsable.RegistroidResponsablePAMECNavigation))]
        public virtual Responsable idResponsablePAMECNavigation { get; set; }
        [ForeignKey(nameof(idResponsableSIC))]
        [InverseProperty(nameof(Responsable.RegistroidResponsableSICNavigation))]
        public virtual Responsable idResponsableSICNavigation { get; set; }
        [InverseProperty("idRegistroNavigation")]
        public virtual ICollection<MiembroComision> MiembroComision { get; set; }
        [InverseProperty("idRegistroNavigation")]
        public virtual ICollection<RegistroPAMEC> RegistroPAMEC { get; set; }
        [InverseProperty("idRegistroNavigation")]
        public virtual ICollection<RegistroSIC> RegistroSIC { get; set; }
        [InverseProperty("idRegistroNavigation")]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMEC { get; set; }
        [InverseProperty("idRegistroNavigation")]
        public virtual ICollection<SeguimientoSIC> SeguimientoSIC { get; set; }
    }
}