// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Responsable", Schema = "pamec")]
    public partial class Responsable
    {
        public Responsable()
        {
            RegistroidResponsablePAMECNavigation = new HashSet<Registro>();
            RegistroidResponsableSICNavigation = new HashSet<Registro>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(100)]
        public string nombre { get; set; }
        [Required]
        [StringLength(50)]
        public string cargo { get; set; }
        [Required]
        [StringLength(50)]
        public string correoElectronico { get; set; }
        [Required]
        [StringLength(15)]
        public string celular { get; set; }

        [InverseProperty(nameof(Registro.idResponsablePAMECNavigation))]
        public virtual ICollection<Registro> RegistroidResponsablePAMECNavigation { get; set; }
        [InverseProperty(nameof(Registro.idResponsableSICNavigation))]
        public virtual ICollection<Registro> RegistroidResponsableSICNavigation { get; set; }
    }
}