// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Sede", Schema = "pamec")]
    public partial class Sede
    {
        [Key]
        public int id { get; set; }
        public int idEntidad { get; set; }
        [Required]
        [StringLength(50)]
        public string codigo { get; set; }
        [Required]
        [StringLength(100)]
        public string nombreComercial { get; set; }
        [Required]
        [StringLength(100)]
        public string direccion { get; set; }
        [Required]
        [StringLength(15)]
        public string telefono { get; set; }
        [Required]
        [StringLength(15)]
        public string localidad { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaInscripcion { get; set; }
        public bool esPrincipal { get; set; }

        [ForeignKey(nameof(idEntidad))]
        [InverseProperty(nameof(Entidad.Sede))]
        public virtual Entidad idEntidadNavigation { get; set; }
    }
}