// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("SeguimientoSIC", Schema = "pamec")]
    public partial class SeguimientoSIC
    {
        [Key]
        public int id { get; set; }
        public int idRegistro { get; set; }
        public int idTipoVisita { get; set; }
        public bool realizoReportes { get; set; }
        public bool realizoAnalisisInfo { get; set; }
        [Required]
        [StringLength(4)]
        public string porcentajeEjecucion { get; set; }
        public bool adelantoAccionesAdminInspVigCon { get; set; }
        public int idDetalleAccionAdmin { get; set; }
        [Required]
        [StringLength(4000)]
        public string causasOrigenActAdmin { get; set; }
        [Required]
        [StringLength(4000)]
        public string observaciones { get; set; }
        public int cargo { get; set; }
        public int responsableSeguimiento { get; set; }
        [Required]
        [StringLength(50)]
        public string correoElectronico { get; set; }
        [Required]
        [StringLength(10)]
        public string celular { get; set; }
        public int idVerificador { get; set; }
        [Column(TypeName = "date")]
        public DateTime fechaCreacion { get; set; }

        [ForeignKey(nameof(idDetalleAccionAdmin))]
        [InverseProperty(nameof(Constante.SeguimientoSICidDetalleAccionAdminNavigation))]
        public virtual Constante idDetalleAccionAdminNavigation { get; set; }
        [ForeignKey(nameof(idRegistro))]
        [InverseProperty(nameof(Registro.SeguimientoSIC))]
        public virtual Registro idRegistroNavigation { get; set; }
        [ForeignKey(nameof(idTipoVisita))]
        [InverseProperty(nameof(Constante.SeguimientoSICidTipoVisitaNavigation))]
        public virtual Constante idTipoVisitaNavigation { get; set; }
        [ForeignKey(nameof(idVerificador))]
        [InverseProperty(nameof(Usuario.SeguimientoSIC))]
        public virtual Usuario idVerificadorNavigation { get; set; }
    }
}