// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Usuario", Schema = "pamec")]
    public partial class Usuario
    {
        public Usuario()
        {
            SeguimientoSIC = new HashSet<SeguimientoSIC>();
            Usuario_Cargo = new HashSet<Usuario_Cargo>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string nombre { get; set; }
        public int idTipoIdentificaicon { get; set; }
        [Required]
        [StringLength(15)]
        public string numIdentificacion { get; set; }
        [Required]
        [StringLength(50)]
        public string telefono { get; set; }
        [Required]
        [StringLength(100)]
        public string correo { get; set; }
        [Required]
        [StringLength(100)]
        public string direccion { get; set; }
        public bool estado { get; set; }
        public int? tipoVinculacion { get; set; }
        public int? idDpendencia { get; set; }

        [ForeignKey(nameof(idDpendencia))]
        [InverseProperty(nameof(Dependencia.Usuario))]
        public virtual Dependencia idDpendenciaNavigation { get; set; }
        [ForeignKey(nameof(idTipoIdentificaicon))]
        [InverseProperty(nameof(Constante.UsuarioidTipoIdentificaiconNavigation))]
        public virtual Constante idTipoIdentificaiconNavigation { get; set; }
        [ForeignKey(nameof(tipoVinculacion))]
        [InverseProperty(nameof(Constante.UsuariotipoVinculacionNavigation))]
        public virtual Constante tipoVinculacionNavigation { get; set; }
        [InverseProperty("idVerificadorNavigation")]
        public virtual ICollection<SeguimientoSIC> SeguimientoSIC { get; set; }
        [InverseProperty("idUsuarioNavigation")]
        public virtual ICollection<Usuario_Cargo> Usuario_Cargo { get; set; }
    }
}