// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Usuario_Cargo", Schema = "pamec")]
    public partial class Usuario_Cargo
    {
        public Usuario_Cargo()
        {
            MiembroComision = new HashSet<MiembroComision>();
            SeguimientoPAMEC = new HashSet<SeguimientoPAMEC>();
        }

        [Key]
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idCargo { get; set; }
        public bool estado { get; set; }

        [ForeignKey(nameof(idCargo))]
        [InverseProperty(nameof(Cargo.Usuario_Cargo))]
        public virtual Cargo idCargoNavigation { get; set; }
        [ForeignKey(nameof(idUsuario))]
        [InverseProperty(nameof(Usuario.Usuario_Cargo))]
        public virtual Usuario idUsuarioNavigation { get; set; }
        [InverseProperty("idUsuarioCargoNavigation")]
        public virtual ICollection<MiembroComision> MiembroComision { get; set; }
        [InverseProperty("idVerificadorNavigation")]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMEC { get; set; }
    }
}